# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_arc <- function(data, params) {
    .Call(`_mapdeck_rcpp_arc`, data, params)
}

rcpp_df_to_geojson_atomise <- function(df, lon, lat) {
    .Call(`_mapdeck_rcpp_df_to_geojson_atomise`, df, lon, lat)
}

rcpp_grid <- function(data, params) {
    .Call(`_mapdeck_rcpp_grid`, data, params)
}

rcpp_hexagon <- function(data, params) {
    .Call(`_mapdeck_rcpp_hexagon`, data, params)
}

rcpp_line <- function(data, params) {
    .Call(`_mapdeck_rcpp_line`, data, params)
}

rcpp_path_geo <- function(data, params) {
    .Call(`_mapdeck_rcpp_path_geo`, data, params)
}

rcpp_pointcloud <- function(data, params) {
    .Call(`_mapdeck_rcpp_pointcloud`, data, params)
}

rcpp_polygon <- function(data, params) {
    .Call(`_mapdeck_rcpp_polygon`, data, params)
}

rcpp_scatterplot_geo <- function(data, params) {
    .Call(`_mapdeck_rcpp_scatterplot_geo`, data, params)
}

rcpp_screengrid <- function(data, params) {
    .Call(`_mapdeck_rcpp_screengrid`, data, params)
}

rcpp_text <- function(data, params) {
    .Call(`_mapdeck_rcpp_text`, data, params)
}

