# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_aggregate_geojson <- function(data, params, geometry_column, digits, layer_name) {
    .Call(`_mapdeck_rcpp_aggregate_geojson`, data, params, geometry_column, digits, layer_name)
}

rcpp_aggregate_geojson_df <- function(data, params, geometry_columns, digits, layer_name) {
    .Call(`_mapdeck_rcpp_aggregate_geojson_df`, data, params, geometry_columns, digits, layer_name)
}

rcpp_aggregate_polyline <- function(data, params, geometry_columns, layer_name) {
    .Call(`_mapdeck_rcpp_aggregate_polyline`, data, params, geometry_columns, layer_name)
}

rcpp_geojson_geojson <- function(data, params, geometry_column, digits) {
    .Call(`_mapdeck_rcpp_geojson_geojson`, data, params, geometry_column, digits)
}

mesh_to_sf <- function(mesh, vertices) {
    .Call(`_mapdeck_mesh_to_sf`, mesh, vertices)
}

rcpp_mesh_geojson <- function(mesh, params, vertices, digits) {
    .Call(`_mapdeck_rcpp_mesh_geojson`, mesh, params, vertices, digits)
}

rcpp_mesh_geojson2 <- function(mesh, vertices) {
    .Call(`_mapdeck_rcpp_mesh_geojson2`, mesh, vertices)
}

rcpp_od_geojson <- function(data, params, geometry_columns, digits, layer_name) {
    .Call(`_mapdeck_rcpp_od_geojson`, data, params, geometry_columns, digits, layer_name)
}

rcpp_od_geojson_df <- function(data, params, geometry_columns, digits, layer_name) {
    .Call(`_mapdeck_rcpp_od_geojson_df`, data, params, geometry_columns, digits, layer_name)
}

rcpp_od_polyline <- function(data, params, geometry_columns, layer_name) {
    .Call(`_mapdeck_rcpp_od_polyline`, data, params, geometry_columns, layer_name)
}

rcpp_path_geojson <- function(data, params, geometry_columns, digits, layer_name) {
    .Call(`_mapdeck_rcpp_path_geojson`, data, params, geometry_columns, digits, layer_name)
}

rcpp_path_polyline <- function(data, params, geometry_columns, layer_name) {
    .Call(`_mapdeck_rcpp_path_polyline`, data, params, geometry_columns, layer_name)
}

rcpp_point_df_columnar <- function(data, params, geometry_columns, digits, layer_name) {
    .Call(`_mapdeck_rcpp_point_df_columnar`, data, params, geometry_columns, digits, layer_name)
}

rcpp_point_sf_columnar <- function(data, params, geometry_columns, digits, layer_name) {
    .Call(`_mapdeck_rcpp_point_sf_columnar`, data, params, geometry_columns, digits, layer_name)
}

rcpp_point_geojson_df <- function(data, params, geometry_columns, digits, layer_name) {
    .Call(`_mapdeck_rcpp_point_geojson_df`, data, params, geometry_columns, digits, layer_name)
}

rcpp_point_polyline <- function(data, params, geometry_columns, layer_name) {
    .Call(`_mapdeck_rcpp_point_polyline`, data, params, geometry_columns, layer_name)
}

rcpp_polygon_geojson <- function(data, params, geometry_columns, digits) {
    .Call(`_mapdeck_rcpp_polygon_geojson`, data, params, geometry_columns, digits)
}

rcpp_polygon_polyline <- function(data, params, geometry_columns) {
    .Call(`_mapdeck_rcpp_polygon_polyline`, data, params, geometry_columns)
}

rcpp_text_geojson <- function(data, params, geometry_columns, digits) {
    .Call(`_mapdeck_rcpp_text_geojson`, data, params, geometry_columns, digits)
}

rcpp_text_geojson_df <- function(data, params, geometry_columns, digits) {
    .Call(`_mapdeck_rcpp_text_geojson_df`, data, params, geometry_columns, digits)
}

rcpp_text_polyline <- function(data, params, geometry_columns) {
    .Call(`_mapdeck_rcpp_text_polyline`, data, params, geometry_columns)
}

