# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_path_geojson <- function(data, data_types, params, geometry_columns) {
    .Call(`_mapdeck_rcpp_path_geojson`, data, data_types, params, geometry_columns)
}

rcpp_polygon_geojson <- function(data, data_types, params, geometry_columns) {
    .Call(`_mapdeck_rcpp_polygon_geojson`, data, data_types, params, geometry_columns)
}

